/*
 *  (c) Copyright 2016-2017 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef KVS_H
#define KVS_H

#include <cstddef> // size_t

#include "nvmm/global_ptr.h"

namespace radixtree {

class KeyValueStore {
public:
    virtual ~KeyValueStore(){};

    static void Start();
    static void Reset();
    static KeyValueStore *MakeKVS(int choice, nvmm::GlobalPtr location);

    virtual int Put (char const *key, size_t const key_len,
		     char const *val, size_t const val_len) = 0;

    virtual int Get (char const *key, size_t const key_len,
		     char *val, size_t &val_len) = 0;

    virtual int Del (char const *key, size_t const key_len) = 0;

    virtual nvmm::GlobalPtr Location () = 0;

    virtual size_t MaxKeyLen() = 0;
    virtual size_t MaxValLen() = 0;
};

} // namespace radixtree

#endif
