/*
 *  (c) Copyright 2016-2017 Hewlett Packard Enterprise Development Company LP.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  As an exception, the copyright holders of this Library grant you permission
 *  to (i) compile an Application with the Library, and (ii) distribute the
 *  Application containing code generated by the Library and added to the
 *  Application during this compilation process under terms of your choice,
 *  provided you also meet the terms and conditions of the Application license.
 *
 */

#ifndef TRANSACTION_MANAGER_H
#define TRANSACTION_MANAGER_H

#include <assert.h>

#include "radixtree/radixtree_libpmem.h"
#include "radixtree/radixtree_fam_atomic.h"
#include "radixtree/radix_tree.h"
#include "radixtree/status.h"

#include "nvmm/memory_manager.h"
#include "nvmm/heap.h"

namespace radixtree {

nvmm::PoolId const TXN_MGR_POOL_ID = 2;
    
class TransactionManager {
public:
    typedef uint64_t tid_t;

    static TransactionManager *getInstance();

    void acquireLock (tid_t tid);
    bool releaseLock (tid_t tid);
    tid_t peakLock ();

    tid_t getNextTid ();
    uint64_t getNextHandleId ();

    Status insertToCatalog (const std::string &indexName, const bool isUnique);
    Status dropFromCatalog (const std::string &indexName);

    Status lookupCatalog (nvmm::GlobalPtr &root, bool &isUnique, const std::string &indexName);

    inline nvmm::MemoryManager *getMmgr() {return mmgr;}
    inline nvmm::Heap *getHeap() {return heap;}

    // for test only!!!
    // delete all existing files and restart the transaction manager
    void Reset();

private:
    void* toLocal(const nvmm::GlobalPtr &gptr);
    uint64_t encodeMultiPtr(const nvmm::GlobalPtr &gptr);
    bool isMultiPtr(const uint64_t &gptr);
    nvmm::GlobalPtr decodeMultiPtr(const uint64_t &gptr);

private:

    static const size_t kRegionSize = 128*1024*1024; // 128MB
    static const size_t kHeapSize = 8*1024*1024*1024L; // 1024MB

    TransactionManager();
    ~TransactionManager();

    void Init(); // start the transaction manager using existing heap if available
    void Final(); // shutdown the transaction manager without deleting the heap

    nvmm::MemoryManager *mmgr;
    nvmm::Heap *heap;
    nvmm::Region *region;

    struct txn_mgr_header
    {
        tid_t glock;
        tid_t tidCounter;
        tid_t handleCounter;
        nvmm::GlobalPtr catalogRoot;
    };

    txn_mgr_header *header;
    nvmm::GlobalPtr catalogRoot;
    RadixTree *catalogIndex;
};

}

#endif
